// Regenerates src/integrations/supabase/firestore/schema.generated.ts from the
// (frozen) Supabase `types.ts`. The Firestore layer needs the column list,
// which columns are nullable, and the foreign keys at RUNTIME (types.ts is
// type-only), so we derive them once instead of maintaining them by hand.
//
//   node scripts/gen-schema.mjs
import { readFileSync, writeFileSync } from "node:fs";

const src = readFileSync("src/integrations/supabase/types.ts", "utf8");
const tablesBlock = src.match(/Tables: \{([\s\S]*?)\n    \};\n    Views/)?.[1];
if (!tablesBlock) throw new Error("Could not locate the Tables block in types.ts");

const tableRe =
  /\n {6}(\w+): \{\n {8}Row: \{([\s\S]*?)\n {8}\};\n {8}Insert: \{[\s\S]*?\n {8}\};\n {8}Update: \{[\s\S]*?\n {8}\};\n {8}Relationships: \[([\s\S]*?)\];\n {6}\};/g;

const out = [];
for (const m of tablesBlock.matchAll(tableRe)) {
  const [, name, rowBody, relBody] = m;
  const columns = [];
  const nullable = [];
  for (const c of rowBody.matchAll(/\n {10}(\w+): ([^\n]+);/g)) {
    columns.push(c[1]);
    if (/\| null$/.test(c[2])) nullable.push(c[1]);
  }
  const rels = [];
  for (const r of relBody.matchAll(
    /columns: \[([^\]]*)\];\s*isOneToOne: (true|false);\s*referencedRelation: "(\w+)";\s*referencedColumns: \[([^\]]*)\];/g,
  )) {
    const list = (s) =>
      s
        .split(",")
        .map((x) => x.trim().replace(/"/g, ""))
        .filter(Boolean);
    rels.push({
      columns: list(r[1]),
      isOneToOne: r[2] === "true",
      referencedRelation: r[3],
      referencedColumns: list(r[4]),
    });
  }
  out.push({ name, columns, nullable, rels });
}

const q = (a) => `[${a.map((x) => JSON.stringify(x)).join(", ")}]`;
let body = `// GENERATED by scripts/gen-schema.mjs from ./../types.ts. Do not edit by hand.
import type { Database } from "../types.ts";

export type TableName = keyof Database["public"]["Tables"] & string;

export type ForeignKey = {
  readonly columns: readonly string[];
  readonly isOneToOne: boolean;
  readonly referencedRelation: TableName;
  readonly referencedColumns: readonly string[];
};

export type TableSchema = {
  readonly columns: readonly string[];
  readonly nullable: readonly string[];
  readonly relationships: readonly ForeignKey[];
};

export const TABLE_SCHEMA = {
`;
for (const t of out) {
  body += `  ${t.name}: {\n    columns: ${q(t.columns)},\n    nullable: ${q(t.nullable)},\n    relationships: [\n`;
  for (const r of t.rels) {
    body += `      { columns: ${q(r.columns)}, isOneToOne: ${r.isOneToOne}, referencedRelation: ${JSON.stringify(r.referencedRelation)}, referencedColumns: ${q(r.referencedColumns)} },\n`;
  }
  body += `    ],\n  },\n`;
}
body += `} as const satisfies Record<TableName, TableSchema>;\n`;
writeFileSync("src/integrations/supabase/firestore/schema.generated.ts", body);
console.log(`wrote ${out.length} tables`);
