/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedActivityRouteImport } from './routes/_authenticated/activity'
import { Route as AuthenticatedCalendarRouteImport } from './routes/_authenticated/calendar'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedDiscoverRouteImport } from './routes/_authenticated/discover'
import { Route as AuthenticatedLibraryRouteImport } from './routes/_authenticated/library'
import { Route as AuthenticatedMonitoringRouteImport } from './routes/_authenticated/monitoring'
import { Route as AuthenticatedOpportunitiesRouteImport } from './routes/_authenticated/opportunities'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedSpeakersRouteImport } from './routes/_authenticated/speakers'
import { Route as AuthenticatedSubmissionsRouteImport } from './routes/_authenticated/submissions'
import { Route as AuthenticatedWorkspaceRouteImport } from './routes/_authenticated/workspace'
import { Route as AuthenticatedOpportunitiesIdRouteImport } from './routes/_authenticated/opportunities_.$id'
import { Route as AuthenticatedSubmissionsIdRouteImport } from './routes/_authenticated/submissions_.$id'
import { Route as AuthenticatedWorkspaceIdRouteImport } from './routes/_authenticated/workspace_.$id'
import { Route as ApiPublicCalendarFeedRouteImport } from './routes/api/public/calendar-feed'
import { Route as ApiPublicHooksDiscoverDailyRouteImport } from './routes/api/public/hooks/discover-daily'
import { Route as ApiPublicHooksEmailDigestRouteImport } from './routes/api/public/hooks/email-digest'
import { Route as ApiPublicHooksMonitorWeeklyRouteImport } from './routes/api/public/hooks/monitor-weekly'
import { Route as ApiPublicHooksTrackerWeeklyRouteImport } from './routes/api/public/hooks/tracker-weekly'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedActivityRoute = AuthenticatedActivityRouteImport.update({
  id: '/activity',
  path: '/activity',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCalendarRoute = AuthenticatedCalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDiscoverRoute = AuthenticatedDiscoverRouteImport.update({
  id: '/discover',
  path: '/discover',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedLibraryRoute = AuthenticatedLibraryRouteImport.update({
  id: '/library',
  path: '/library',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMonitoringRoute = AuthenticatedMonitoringRouteImport.update({
  id: '/monitoring',
  path: '/monitoring',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedOpportunitiesRoute =
  AuthenticatedOpportunitiesRouteImport.update({
    id: '/opportunities',
    path: '/opportunities',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSpeakersRoute = AuthenticatedSpeakersRouteImport.update({
  id: '/speakers',
  path: '/speakers',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSubmissionsRoute =
  AuthenticatedSubmissionsRouteImport.update({
    id: '/submissions',
    path: '/submissions',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedWorkspaceRoute = AuthenticatedWorkspaceRouteImport.update({
  id: '/workspace',
  path: '/workspace',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedOpportunitiesIdRoute =
  AuthenticatedOpportunitiesIdRouteImport.update({
    id: '/opportunities_/$id',
    path: '/opportunities/$id',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSubmissionsIdRoute =
  AuthenticatedSubmissionsIdRouteImport.update({
    id: '/submissions_/$id',
    path: '/submissions/$id',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedWorkspaceIdRoute =
  AuthenticatedWorkspaceIdRouteImport.update({
    id: '/workspace_/$id',
    path: '/workspace/$id',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const ApiPublicCalendarFeedRoute = ApiPublicCalendarFeedRouteImport.update({
  id: '/api/public/calendar-feed',
  path: '/api/public/calendar-feed',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicHooksDiscoverDailyRoute =
  ApiPublicHooksDiscoverDailyRouteImport.update({
    id: '/api/public/hooks/discover-daily',
    path: '/api/public/hooks/discover-daily',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksEmailDigestRoute =
  ApiPublicHooksEmailDigestRouteImport.update({
    id: '/api/public/hooks/email-digest',
    path: '/api/public/hooks/email-digest',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksMonitorWeeklyRoute =
  ApiPublicHooksMonitorWeeklyRouteImport.update({
    id: '/api/public/hooks/monitor-weekly',
    path: '/api/public/hooks/monitor-weekly',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksTrackerWeeklyRoute =
  ApiPublicHooksTrackerWeeklyRouteImport.update({
    id: '/api/public/hooks/tracker-weekly',
    path: '/api/public/hooks/tracker-weekly',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/activity': typeof AuthenticatedActivityRoute
  '/calendar': typeof AuthenticatedCalendarRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/discover': typeof AuthenticatedDiscoverRoute
  '/library': typeof AuthenticatedLibraryRoute
  '/monitoring': typeof AuthenticatedMonitoringRoute
  '/opportunities': typeof AuthenticatedOpportunitiesRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/speakers': typeof AuthenticatedSpeakersRoute
  '/submissions': typeof AuthenticatedSubmissionsRoute
  '/workspace': typeof AuthenticatedWorkspaceRoute
  '/opportunities/$id': typeof AuthenticatedOpportunitiesIdRoute
  '/submissions/$id': typeof AuthenticatedSubmissionsIdRoute
  '/workspace/$id': typeof AuthenticatedWorkspaceIdRoute
  '/api/public/calendar-feed': typeof ApiPublicCalendarFeedRoute
  '/api/public/hooks/discover-daily': typeof ApiPublicHooksDiscoverDailyRoute
  '/api/public/hooks/email-digest': typeof ApiPublicHooksEmailDigestRoute
  '/api/public/hooks/monitor-weekly': typeof ApiPublicHooksMonitorWeeklyRoute
  '/api/public/hooks/tracker-weekly': typeof ApiPublicHooksTrackerWeeklyRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/activity': typeof AuthenticatedActivityRoute
  '/calendar': typeof AuthenticatedCalendarRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/discover': typeof AuthenticatedDiscoverRoute
  '/library': typeof AuthenticatedLibraryRoute
  '/monitoring': typeof AuthenticatedMonitoringRoute
  '/opportunities': typeof AuthenticatedOpportunitiesRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/speakers': typeof AuthenticatedSpeakersRoute
  '/submissions': typeof AuthenticatedSubmissionsRoute
  '/workspace': typeof AuthenticatedWorkspaceRoute
  '/opportunities/$id': typeof AuthenticatedOpportunitiesIdRoute
  '/submissions/$id': typeof AuthenticatedSubmissionsIdRoute
  '/workspace/$id': typeof AuthenticatedWorkspaceIdRoute
  '/api/public/calendar-feed': typeof ApiPublicCalendarFeedRoute
  '/api/public/hooks/discover-daily': typeof ApiPublicHooksDiscoverDailyRoute
  '/api/public/hooks/email-digest': typeof ApiPublicHooksEmailDigestRoute
  '/api/public/hooks/monitor-weekly': typeof ApiPublicHooksMonitorWeeklyRoute
  '/api/public/hooks/tracker-weekly': typeof ApiPublicHooksTrackerWeeklyRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/activity': typeof AuthenticatedActivityRoute
  '/_authenticated/calendar': typeof AuthenticatedCalendarRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/discover': typeof AuthenticatedDiscoverRoute
  '/_authenticated/library': typeof AuthenticatedLibraryRoute
  '/_authenticated/monitoring': typeof AuthenticatedMonitoringRoute
  '/_authenticated/opportunities': typeof AuthenticatedOpportunitiesRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/_authenticated/speakers': typeof AuthenticatedSpeakersRoute
  '/_authenticated/submissions': typeof AuthenticatedSubmissionsRoute
  '/_authenticated/workspace': typeof AuthenticatedWorkspaceRoute
  '/_authenticated/opportunities_/$id': typeof AuthenticatedOpportunitiesIdRoute
  '/_authenticated/submissions_/$id': typeof AuthenticatedSubmissionsIdRoute
  '/_authenticated/workspace_/$id': typeof AuthenticatedWorkspaceIdRoute
  '/api/public/calendar-feed': typeof ApiPublicCalendarFeedRoute
  '/api/public/hooks/discover-daily': typeof ApiPublicHooksDiscoverDailyRoute
  '/api/public/hooks/email-digest': typeof ApiPublicHooksEmailDigestRoute
  '/api/public/hooks/monitor-weekly': typeof ApiPublicHooksMonitorWeeklyRoute
  '/api/public/hooks/tracker-weekly': typeof ApiPublicHooksTrackerWeeklyRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/activity'
    | '/calendar'
    | '/dashboard'
    | '/discover'
    | '/library'
    | '/monitoring'
    | '/opportunities'
    | '/settings'
    | '/speakers'
    | '/submissions'
    | '/workspace'
    | '/opportunities/$id'
    | '/submissions/$id'
    | '/workspace/$id'
    | '/api/public/calendar-feed'
    | '/api/public/hooks/discover-daily'
    | '/api/public/hooks/email-digest'
    | '/api/public/hooks/monitor-weekly'
    | '/api/public/hooks/tracker-weekly'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/activity'
    | '/calendar'
    | '/dashboard'
    | '/discover'
    | '/library'
    | '/monitoring'
    | '/opportunities'
    | '/settings'
    | '/speakers'
    | '/submissions'
    | '/workspace'
    | '/opportunities/$id'
    | '/submissions/$id'
    | '/workspace/$id'
    | '/api/public/calendar-feed'
    | '/api/public/hooks/discover-daily'
    | '/api/public/hooks/email-digest'
    | '/api/public/hooks/monitor-weekly'
    | '/api/public/hooks/tracker-weekly'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/activity'
    | '/_authenticated/calendar'
    | '/_authenticated/dashboard'
    | '/_authenticated/discover'
    | '/_authenticated/library'
    | '/_authenticated/monitoring'
    | '/_authenticated/opportunities'
    | '/_authenticated/settings'
    | '/_authenticated/speakers'
    | '/_authenticated/submissions'
    | '/_authenticated/workspace'
    | '/_authenticated/opportunities_/$id'
    | '/_authenticated/submissions_/$id'
    | '/_authenticated/workspace_/$id'
    | '/api/public/calendar-feed'
    | '/api/public/hooks/discover-daily'
    | '/api/public/hooks/email-digest'
    | '/api/public/hooks/monitor-weekly'
    | '/api/public/hooks/tracker-weekly'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  ApiPublicCalendarFeedRoute: typeof ApiPublicCalendarFeedRoute
  ApiPublicHooksDiscoverDailyRoute: typeof ApiPublicHooksDiscoverDailyRoute
  ApiPublicHooksEmailDigestRoute: typeof ApiPublicHooksEmailDigestRoute
  ApiPublicHooksMonitorWeeklyRoute: typeof ApiPublicHooksMonitorWeeklyRoute
  ApiPublicHooksTrackerWeeklyRoute: typeof ApiPublicHooksTrackerWeeklyRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/activity': {
      id: '/_authenticated/activity'
      path: '/activity'
      fullPath: '/activity'
      preLoaderRoute: typeof AuthenticatedActivityRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/calendar': {
      id: '/_authenticated/calendar'
      path: '/calendar'
      fullPath: '/calendar'
      preLoaderRoute: typeof AuthenticatedCalendarRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/discover': {
      id: '/_authenticated/discover'
      path: '/discover'
      fullPath: '/discover'
      preLoaderRoute: typeof AuthenticatedDiscoverRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/library': {
      id: '/_authenticated/library'
      path: '/library'
      fullPath: '/library'
      preLoaderRoute: typeof AuthenticatedLibraryRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/monitoring': {
      id: '/_authenticated/monitoring'
      path: '/monitoring'
      fullPath: '/monitoring'
      preLoaderRoute: typeof AuthenticatedMonitoringRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/opportunities': {
      id: '/_authenticated/opportunities'
      path: '/opportunities'
      fullPath: '/opportunities'
      preLoaderRoute: typeof AuthenticatedOpportunitiesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/speakers': {
      id: '/_authenticated/speakers'
      path: '/speakers'
      fullPath: '/speakers'
      preLoaderRoute: typeof AuthenticatedSpeakersRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/submissions': {
      id: '/_authenticated/submissions'
      path: '/submissions'
      fullPath: '/submissions'
      preLoaderRoute: typeof AuthenticatedSubmissionsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/workspace': {
      id: '/_authenticated/workspace'
      path: '/workspace'
      fullPath: '/workspace'
      preLoaderRoute: typeof AuthenticatedWorkspaceRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/opportunities_/$id': {
      id: '/_authenticated/opportunities_/$id'
      path: '/opportunities/$id'
      fullPath: '/opportunities/$id'
      preLoaderRoute: typeof AuthenticatedOpportunitiesIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/submissions_/$id': {
      id: '/_authenticated/submissions_/$id'
      path: '/submissions/$id'
      fullPath: '/submissions/$id'
      preLoaderRoute: typeof AuthenticatedSubmissionsIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/workspace_/$id': {
      id: '/_authenticated/workspace_/$id'
      path: '/workspace/$id'
      fullPath: '/workspace/$id'
      preLoaderRoute: typeof AuthenticatedWorkspaceIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/public/calendar-feed': {
      id: '/api/public/calendar-feed'
      path: '/api/public/calendar-feed'
      fullPath: '/api/public/calendar-feed'
      preLoaderRoute: typeof ApiPublicCalendarFeedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/discover-daily': {
      id: '/api/public/hooks/discover-daily'
      path: '/api/public/hooks/discover-daily'
      fullPath: '/api/public/hooks/discover-daily'
      preLoaderRoute: typeof ApiPublicHooksDiscoverDailyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/email-digest': {
      id: '/api/public/hooks/email-digest'
      path: '/api/public/hooks/email-digest'
      fullPath: '/api/public/hooks/email-digest'
      preLoaderRoute: typeof ApiPublicHooksEmailDigestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/monitor-weekly': {
      id: '/api/public/hooks/monitor-weekly'
      path: '/api/public/hooks/monitor-weekly'
      fullPath: '/api/public/hooks/monitor-weekly'
      preLoaderRoute: typeof ApiPublicHooksMonitorWeeklyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/tracker-weekly': {
      id: '/api/public/hooks/tracker-weekly'
      path: '/api/public/hooks/tracker-weekly'
      fullPath: '/api/public/hooks/tracker-weekly'
      preLoaderRoute: typeof ApiPublicHooksTrackerWeeklyRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedActivityRoute: typeof AuthenticatedActivityRoute
  AuthenticatedCalendarRoute: typeof AuthenticatedCalendarRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedDiscoverRoute: typeof AuthenticatedDiscoverRoute
  AuthenticatedLibraryRoute: typeof AuthenticatedLibraryRoute
  AuthenticatedMonitoringRoute: typeof AuthenticatedMonitoringRoute
  AuthenticatedOpportunitiesRoute: typeof AuthenticatedOpportunitiesRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
  AuthenticatedSpeakersRoute: typeof AuthenticatedSpeakersRoute
  AuthenticatedSubmissionsRoute: typeof AuthenticatedSubmissionsRoute
  AuthenticatedWorkspaceRoute: typeof AuthenticatedWorkspaceRoute
  AuthenticatedOpportunitiesIdRoute: typeof AuthenticatedOpportunitiesIdRoute
  AuthenticatedSubmissionsIdRoute: typeof AuthenticatedSubmissionsIdRoute
  AuthenticatedWorkspaceIdRoute: typeof AuthenticatedWorkspaceIdRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedActivityRoute: AuthenticatedActivityRoute,
  AuthenticatedCalendarRoute: AuthenticatedCalendarRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedDiscoverRoute: AuthenticatedDiscoverRoute,
  AuthenticatedLibraryRoute: AuthenticatedLibraryRoute,
  AuthenticatedMonitoringRoute: AuthenticatedMonitoringRoute,
  AuthenticatedOpportunitiesRoute: AuthenticatedOpportunitiesRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
  AuthenticatedSpeakersRoute: AuthenticatedSpeakersRoute,
  AuthenticatedSubmissionsRoute: AuthenticatedSubmissionsRoute,
  AuthenticatedWorkspaceRoute: AuthenticatedWorkspaceRoute,
  AuthenticatedOpportunitiesIdRoute: AuthenticatedOpportunitiesIdRoute,
  AuthenticatedSubmissionsIdRoute: AuthenticatedSubmissionsIdRoute,
  AuthenticatedWorkspaceIdRoute: AuthenticatedWorkspaceIdRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  ApiPublicCalendarFeedRoute: ApiPublicCalendarFeedRoute,
  ApiPublicHooksDiscoverDailyRoute: ApiPublicHooksDiscoverDailyRoute,
  ApiPublicHooksEmailDigestRoute: ApiPublicHooksEmailDigestRoute,
  ApiPublicHooksMonitorWeeklyRoute: ApiPublicHooksMonitorWeeklyRoute,
  ApiPublicHooksTrackerWeeklyRoute: ApiPublicHooksTrackerWeeklyRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
